name: omohide_map_flutter
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  go_router: ^16.0.0
  dio: ^5.8.0+1
  supabase_flutter: ^2.9.1
  google_sign_in: ^6.2.1
  envied: ^1.1.1
  image_picker: ^1.1.2
  geolocator: ^13.0.1
  permission_handler: ^12.0.1
  geocoding: ^3.0.0
  mime: ^2.0.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  envied_generator: ^1.1.1
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
