// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSQjSE6qV6fGBdw8Gmbz7PCMudwngqshU',
    appId: '1:462899392087:web:d5c03ed598ddf55a62fd12',
    messagingSenderId: '462899392087',
    projectId: 'omohide-map-app-505a4',
    authDomain: 'omohide-map-app-505a4.firebaseapp.com',
    storageBucket: 'omohide-map-app-505a4.firebasestorage.app',
    measurementId: 'G-H25EPTVF2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUzP4C_kDwvedYMqp8OnlXM8CZlMeKPzE',
    appId: '1:462899392087:android:8a3998487b531ed862fd12',
    messagingSenderId: '462899392087',
    projectId: 'omohide-map-app-505a4',
    storageBucket: 'omohide-map-app-505a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAcJgA-5b7xwA77I_B7mQ2un8ogBOtJso',
    appId: '1:462899392087:ios:8688f63b1d66538e62fd12',
    messagingSenderId: '462899392087',
    projectId: 'omohide-map-app-505a4',
    storageBucket: 'omohide-map-app-505a4.firebasestorage.app',
    iosBundleId: 'com.example.omohideMapFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAcJgA-5b7xwA77I_B7mQ2un8ogBOtJso',
    appId: '1:462899392087:ios:8688f63b1d66538e62fd12',
    messagingSenderId: '462899392087',
    projectId: 'omohide-map-app-505a4',
    storageBucket: 'omohide-map-app-505a4.firebasestorage.app',
    iosBundleId: 'com.example.omohideMapFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSQjSE6qV6fGBdw8Gmbz7PCMudwngqshU',
    appId: '1:462899392087:web:bca5781dec99104162fd12',
    messagingSenderId: '462899392087',
    projectId: 'omohide-map-app-505a4',
    authDomain: 'omohide-map-app-505a4.firebaseapp.com',
    storageBucket: 'omohide-map-app-505a4.firebasestorage.app',
    measurementId: 'G-FH4MXEJZXG',
  );
}
